version: "3"

services:

  queue:
    image: rabbitmq:management
    container_name: rabbitmq_queue
    environment:
      RABBITMQ_DEFAULT_USERNAME: blended
      RABBITMQ_DEFAULT_PASSWORD: makeitpopweBLENDED!1
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      restart_policy:
        condition: on-failure
  
  cache:
    image: redis
    container_name: redis_cache
    command: redis-server --requirepass makeitpopweBLENDED!1
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    deploy:
      restart_policy:
        condition: on-failure


volumes:
  cache_data:
  