version: "3"

services:

  queue:
    build:
      context: .
      dockerfile: RabbitDockerfile
    container_name: rabbitmq_queue
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
  
  cache:
    image: redis
    container_name: redis_cache
    command: redis-server --requirepass makeitpopweBLENDED!1
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    restart: unless-stopped


volumes:
  cache_data:
  