version: "3"

services:
  server_1:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: server_1
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - default
      - simpli_api
    restart: always

  server_2:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: server_2
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    networks:
      - default
      - simpli_api
    restart: always

  server_3:
    build:
      context: .
      dockerfile: Dockerfile3
    container_name: server_3
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    networks:
      - default
      - simpli_api
    restart: always

networks:
  simpli_api:
    driver: bridge